config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'
  get 'demo', to: 'welcome#demo'
  resources :users
  get '/users/:id/finish', to: 'users#finish', as: 'users_finish'
  post '/users/:id/finish', to: 'users#initialize_new_user'


  resources :user_interests, only: [:create, :destroy]
  resources :interests, only: [:show]

  resources :matches, only: [:index, :create, :update, :destroy]


  resources :conversations, only: [:index, :destroy] do
    resources :messages, only: [:index, :create, :destroy]
  end

  resources :searches, only: [:index]

  get '/auth/linkedin/callback', to: 'sessions#create', as: 'sessions_create'
  get '/auth/failure', to:'sessions#failure'
  get '/logout', to: 'sessions#destroy', as: 'logout'
  get '/deleteuserinterest/:id', to: 'user_interests#destroy', as: 'user_interest_delete'

end

app/models/conversation.rb
class Conversation < ActiveRecord::Base
  belongs_to :mentor, class_name: 'User'
  belongs_to :mentee, class_name: 'User'
  has_one :match

  has_many :messages, dependent: :destroy

  validates_uniqueness_of :mentor_id, :scope => :mentee_id

  scope :between, -> (mentor_id, mentee_id) do
    where("(conversations.mentor_id = ? AND conversations.mentee_id =?) OR (conversations.mentor_id = ? AND conversations.mentee_id =?)", mentor_id, mentee_id, mentee_id, mentor_id)
  end

  def unread_message_for_user(user_id)
    self.messages.where(read: false).where('user_id != ?', user_id)
  end

  # def unread_messages?
  # 	messages.where(read: false) && messages.last.user_id != current_user.id
  # end

  def has_new_unread_message(user)
    if self.messages.any?
        if !self.messages.last.read && self.messages.last.user != user then 'warning'
        else
          ''
        end
    else
      return ''
    end
  end



end

app/controllers/conversations_controller.rb
class ConversationsController < ApplicationController
  before_action :allow_user, :finish_profile

  layout "conversations"

  def index
    @visible_conversations = current_user.sorted_conversations
  end

end

app/helpers/conversations_helper.rb
module ConversationsHelper
end

app/views/conversations/index.html.erb
<div class="container">
  <h1 class="text-center">Inbox</h1>
  <div class='row'>
    <% @visible_conversations.each do |conversation| %>
      <% if mentor? %>
      <div class="row">
        <p class="small-1 columns"></p>
        <a href="/users/<%=conversation.mentee.id%>">
          <div class="small-4 columns">
            <br>
            <%=image_tag conversation.mentee.picture_url, size:"80x80" %><br>
          </div>
        </a>
        <div class="small-7 columns">
          <br>
          <%= link_to(conversation_messages_path(conversation.id)) do %>
        <div class="row">
            <div class="<%= conversation.has_new_unread_message(current_user) %> button small-8 columns">
              <i class="step fi-mail size-36"></i><br><b><%= conversation.mentee.first_name %> <%= conversation.mentee.last_name %></b>
            </div>
          <% end %>
          </div>
        </div>
      </div>


      <% else %>

      <div class="row">
        <p class="small-1 columns"></p>
        <a href="/users/<%=conversation.mentor.id%>">
        <div class="small-4 columns">
          <br>
          <%=image_tag conversation.mentor.picture_url, size:"80x80"  %>
        </div>
        </a>
        <div class="small-7 columns">
          <br>
     <%= link_to(conversation_messages_path(conversation.id)) do %>
        <div class="row">
            <div class="<%= conversation.has_new_unread_message(current_user) %> button small-8 columns">
              <i class="step fi-mail size-36"></i><br><b><%= conversation.mentor.first_name %> <%= conversation.mentor.last_name %></b>
            </div>
          <% end %>
          </div>
        </div>
      </div>
      <% end %>
<hr class="style-two">

    <% end %>
  </div>


</div>