config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'
  get 'demo', to: 'welcome#demo'
  resources :users
  get '/users/:id/finish', to: 'users#finish', as: 'users_finish'
  post '/users/:id/finish', to: 'users#initialize_new_user'


  resources :user_interests, only: [:create, :destroy]
  resources :interests, only: [:show]

  resources :matches, only: [:index, :create, :update, :destroy]


  resources :conversations, only: [:index, :destroy] do
    resources :messages, only: [:index, :create, :destroy]
  end

  resources :searches, only: [:index]

  get '/auth/linkedin/callback', to: 'sessions#create', as: 'sessions_create'
  get '/auth/failure', to:'sessions#failure'
  get '/logout', to: 'sessions#destroy', as: 'logout'
  get '/deleteuserinterest/:id', to: 'user_interests#destroy', as: 'user_interest_delete'

end

app/models/user.rb
class User < ActiveRecord::Base
  validates :first_name,
            :last_name,
            :picture_url,
            :public_profile_url,
            :status,
            :email,
            :linkedin_id, presence: true
  validates :linkedin_id, :email, uniqueness: true

  has_many :user_interests
  has_many :interests, through: :user_interests

  has_many :conversations
  has_many :messages
  accepts_nested_attributes_for :user_interests

  def return_opposite_type(current_user)
    if current_user.type == "Mentor"
      User.where(type: "Mentee")
    else
      User.where(type: "Mentor")
    end
  end


#move this to the controller
  def self.find_or_create_from_auth_hash(auth)
    if User.find_by(linkedin_id: auth['uid'])
      User.find_by(linkedin_id: auth['uid'])
      # User.where(linkedin_id: auth['uid']).update_attributes(picture_url: auth.extra.raw_info.pictureUrls.values.last.first)
    else
      @user = User.new()
      @user.linkedin_id = auth['uid'] ||= ""
      @user.email = auth['info']['email'] ||= ""
      @user.first_name = auth['info']['first_name'] ||= ""
      @user.last_name = auth['info']['last_name'] ||= ""
      @user.location = auth['info']['location'] ||= ""
      @user.industry = auth['info']['industry'] ||= ""
      @user.picture_url = auth.extra.raw_info.pictureUrls.values.last.first ||= ""
      @user.public_profile_url = auth['info']['urls']['public_profile'] ||= ""
      return @user if @user.save
    end
  end

  def self.search(search)
    User.joins(:interests).where("first_name || email || last_name || industry || current_company || current_title || mission_statement || location || interests.name LIKE ?", "%#{search}%")

    #  User.joins(:interests).where("interests.name LIKE ?", "%#{search}%")
  end


  def unread_conversations_nav_notification
    if self.conversations.any?{ |convo| convo.unread_message_for_user(self.id).length > 0 }
      return 'notification-for-new-message-or-request'
    else
      return ''
    end
  end

  def unread_conversations_button_notification
    if self.conversations.any?{ |convo| convo.unread_message_for_user(self.id).length > 0 }
      return 'warning'
    else
      return ''
    end
  end

  def sorted_conversations
    accepted_matches = self.accepted_matches
    conversations_to_display = []
    accepted_matches.each do |match|
      conversations_to_display << match.conversation
    end
    conversations_to_display.sort_by do |conv|
      if conv.messages.last != nil
        conv.messages.last.created_at
      else
        conv.created_at
      end
    end
    return conversations_to_display.reverse
  end

  def common_interests(comparison_user)
    user_interest_difference = self.interests - comparison_user.interests
    common_interests = self.interests - user_interest_difference
    common_interests.count
  end

  def users_sorted_by_common_interests_with_score(collection_of_users)
    users_with_commonality_to_current = {}
    bots = [User.find(1), User.find(2)]
    collection_of_users -= bots

    collection_of_users.each_with_index do |comparison_user, idx|
      v = self.common_interests(comparison_user)
      k = comparison_user
      users_with_commonality_to_current[k] = v
    end
    users_with_commonality_to_current.sort_by {|key, value| value }.reverse
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :finish_profile, only: [:index, :show, :edit, :update, :destroy]

  def index
    if mentor?
      available_users = Mentee.where(status: 'available')
    else
      available_users = Mentor.where(status: 'available')
    end

    @users = current_user.users_sorted_by_common_interests_with_score(available_users)
  end


  def new
    @user = User.new()
  end


  def create
    @user = User.new()
    if @user.save
      redirect_to users_path
    # else
      # @errors = @user.errors.full_messages
      # render 'new'
    end
  end


  def show
    @user = User.find(params[:id])
    @interests = Interest.all
    if request.xhr?
      render partial: 'interest_option_form', locals: {interests: @interests, user: @user}, layout: false
    end
  end


  def edit
    @user = User.find(params[:id])
    redirect_unless_editing_or_deleting_own(@user)
  end


  def update

    @user = User.find(params[:id])
    redirect_unless_editing_or_deleting_own(@user)

    @user.assign_attributes(user_params)
    params[:user][:status] == "available" ? @user.status = "available" : @user.status = "unavailable"

    if @user.save
      redirect_to user_path(current_user)
    else
      render 'edit'
    end
  end


  def destroy
    @user = User.find(params[:id])
    redirect_unless_editing_or_deleting_own(@user)

    @user.destroy
    redirect '/users'
  end

  def finish
    if needs_type?
      render 'finish', layout: "finish"
    else
      redirect_to root_path
    end
  end

  def initialize_new_user
    @user = User.find(params[:id])
    redirect_unless_editing_or_deleting_own(@user)

    @user.assign_attributes(user_params)
    params[:user][:type] == "Mentor" ? @user.type = "Mentor" : @user.type = "Mentee"
      # creates welcome bot Accepted Match
        @user.type == "Mentor" ? @bot = User.find(1) : @bot = User.find(2)

        @match = AcceptedMatch.new(receiver: @user, initiator: @bot )

        if @user.type == "Mentor"
          @match.mentor_id = @user.id
          @match.mentee_id = @bot.id
        else
          @match.mentor_id = @bot.id
          @match.mentee_id = @user.id
        end


    if @user.save && @match.save
        # Creates conversation and initial message between Bot and new user
        # for new users to avoid empty inbox bug

        @convo = Conversation.find_or_create_by(mentor: @match.mentor, mentee: @match.mentee)
        @match.update_attributes(conversation_id: @convo.id)
        Message.create(body:"Welcome to Mentorship, where mentors and people seeking mentorship connect!\n
                             Make sure to complete your profile and add your professional interests to get noticed more quickly.\n
                             I hope that you enjoy our site, and please email support@mentorship-app.com if you have any questions or concerns!\n
                             With love from the internet,\n
                             Welcome Bot\n",
                    conversation_id: @convo.id,
                    user_id: @bot.id,
                    read: false)

      redirect_to root_path
    else
      render 'finish'
    end
  end

  private
  def user_params
    params.require(:user).permit(:first_name,
                                 :last_name,
                                 :location,
                                 :industry,
                                 :picture_url,
                                 :public_profile_url,
                                 :current_title,
                                 :current_company,
                                 :type,
                                 :status,
                                 :mission_statement,
                                 :user_interests)
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_interest_option_form.html.erb
<select name="interest_id">
  <% (@interests - @user.interests).each do |int| %>
    <option value="<%=int.id%>"><%=int.name%></option>
  <%end%>
</select>

app/views/users/_interests.html.erb
<%= form_for :user do |f| %>
  <table>
    <tr>
      <td>
        Add some interests here!
      </td>
      <td><%=options_for_select(Interest.all, :id, :name) %>
      </td>
    </tr>
  </table>
<% end %>

app/views/users/edit.html.erb
<h1 class="text-center"><b><%= @user.first_name %> <%= @user.last_name %></b> | Editing Profile </h1>
<br>

<!-- <i class="step fi-pencil size-24"></i> -->
<!-- If errors - place here -->

    <div class="small-12 columns">
      <%= form_for(:user, url: user_path(@user), html:{method:"put"}) do |f| %>
        <div class="row">
          <p class="small-12 columns text-center">Do you want your profile <br> shown to prospective <%= current_user.type == "Mentor" ? "Seekers" : "Mentors"%>?</p>
        </div>

        <div class="row">
          <p class="small-1 columns text-center"></p>
          <div class="small-3 columns text-center">
            <i class="step fi-dislike size-48 yes-no-selector-thumbs"></i>
          </div>
          <label class="ios7-switch small-4 columns text-center" style="font-size: 36px";>
            <input type="checkbox" name= "user[status]" value="available" checked>
            <span></span>
          </label>
          <div class="small-3 columns text-center">
            <i class="step fi-like size-48 yes-no-selector-thumbs"></i>
          </div>
          <p class="small-1 columns text-center"></p>
        </div>

        <table class="text-left" id="users-edit-form-table">
          <tr class="row">
            <td class="small-4 columns"><small> First Name</small></td>
            <td class="small-8 columns"><%= f.text_field :first_name, :placeholder => "First Name" %></td>
          </tr>
          <tr class="row">
            <td class="small-4 columns"><small> Last Name</small></td>
            <td class="small-8 columns"><%= f.text_field :last_name, :placeholder => "Last Name" %></td>
          </tr>
          <tr class="row">
            <td class="small-4 columns"><small> Location</small></td>
            <td class="small-8 columns"><%= f.text_field :location, :placeholder => "Location" %></td>
          </tr>
          <tr class="row">
            <td class="small-4 columns"><small> Industry</small></td>
            <td class="small-8 columns"><%= f.text_field :industry, :placeholder => "Industry" %></td>
          </tr>
          <tr class="row">
            <td class="small-4 columns"><small> Current Title</small></td>
            <td class="small-8 columns"><%= f.text_field :current_title, :placeholder => "Current Title" %></td>
          </tr>
          <tr class="row">
            <td class="small-4 columns"><small> Current Company</small></td>
            <td class="small-8 columns"><%= f.text_field :current_company, :placeholder => "Current Company" %></td>
          </tr>
          <tr class="row">
            <td class="small-4 columns"><small> Mission Statement</small></td>
            <td class="small-8 columns"><%= f.text_field :mission_statement, :placeholder => "Mission Statement" %></td>
          </tr>
        </table>
        <%= f.submit class: "button expanded" %>
      <% end %>

<% if @errors %>
  <% @errors.each do |error| %>
    <div class="row">
      <div class="small-3 columns text-center">
        <i id="error-glyphicon-notification" class="step fi-alert size-72"></i>
      </div>
      <div class="small-9 columns">
        <b><%=error.full_messages%></b>
      </div>
    </div>
    <hr class="style-two">
  <% end %>
<% end %>

<hr class="style-three">
  <div class="row">
    <p class="text-center">Click below to remove one of your interests:</p>
    <div class="small-12 columns text-center" id="user-edit-remove-interest-container">
      <% @user.user_interests.each do |user_interest| %>
        <div class="small-6 columns">
          <%= link_to "#{user_interest.interest.name}", user_interest_delete_path(user_interest), :class => "button expanded warning professional-interest-button" %>
        </div>
      <% end %>
    </div>
  </div>
<% if current_user.interests.length > 0 %>
<% end %>
<hr class="style-three">

app/views/users/finish.html.erb
<link href='https://fonts.googleapis.com/css?family=Open+Sans' rel='stylesheet' type='text/css'>

<% if @errors %>
    <% @errors.each do |error| %>
    <br>
    <div class="row">
      <p class="small-2 columns text-center"></p>
      <div class="small-3 columns text-center">
        <i id="error-glyphicon-notification" class="step fi-alert size-36"></i>
      </div>
      <div class="small-5 columns text-center">
        <b><%=error%></b>
      </div>
      <p class="small-2 columns text-center"></p>
    </div>
  <% end %>
<% end %>

<div style="font-family:Open Sans, sans-serif;">
  <h1 class="text-center">Finish Your Profile</h1>
<hr class="style-two">

<%= form_for :user do |f| %>

<div class="row">
  <div class="text-center">
    <div class="button-group toggle" data-toggle="buttons-radio">
      <div class="small-6 columns">
        <p>
          <input type="radio" id="r1" name="user[type]" value="Mentee" data-toggle="button">
          <label class="button expanded" for="r1"><strong>I Am Seeking<br>Mentorship</strong></label>
        </p>
      </div>
      <div class="small-6 columns">
        <p>
          <input type="radio" id="r2" name="user[type]" value="Mentor" data-toggle="button">
          <label class="button expanded" for="r2"><strong>I Am Offering<br>Mentorship</strong></label>
        </p>
      </div>
    </div>
  </div>
</div>

  <div class="row">
    <div class="small-12 columns">
      <p class="text-center">Tell us about what you're looking for:</p>
    </div>
  </div>
  <div class="row">
    <div class="small-12 columns">
      <%= f.text_field :mission_statement %>
    </div>
  </div>

<table class="text-left">
  <tr class="row">
    <td class="small-4 columns">
      <small>Current position:</small>
    </td>
    <td class="small-8 columns">
      <%= f.text_field :current_title %>
    </td>
  </tr>
  <tr class="row">
    <td class="small-4 columns">
      <small>Current company:</small>
    </td>
    <td class="small-8 columns">
      <%= f.text_field :current_company %>
    </td>
  </tr>
</table>

<h3><b><%= f.submit value="Finish my Profile!", class: "button expanded" %></b></h3>
<% end %>
</div>

app/views/users/index.html.erb
<div class="container">
<h1 class="text-center"><%= current_user.type == "Mentor" ? "Seeker" : "Mentor"%> Matches</h1>
<br>

  <% @users.each do |user| %>
    <a href="/users/<%= "#{user[0].id}" %>">
      <div class="row">
        <p class="small-1 columns"></p>
        <div class="small-4 columns">
          <%=image_tag user[0].picture_url %>
        </div>
        <div class="small-7 columns">
          <b><%= user[0].first_name %> <%= user[0].last_name %></b><br>
          <small><%= user[0].current_title %> at</small><br>
          <b><%= user[0].current_company%></b><br>
          <small><%= user[0].location %></small><br>
        </div>
      </div>
    </a>

    <hr class="style-two">

    <div class="row">
      <div class="small-12 small-centered columns text-center">
        <i><%= user[0].mission_statement %></i>
      </div>
    </div>
    <div class="row">
      <div class="small-12 small-centered columns text-center">
        <% if user[1] > 0 %>
        <small><b>You have <%= user[1] %> <%= user[1] != 1 ? 'interests' : 'interest'%> in common</b></small>
        <% else %>
        <small><b>You have no interests in common</b></small>
        <% end %>
      </div>
    </div>

    <hr class="style-two">

    <div class="row">
      <div class="small-12 columns">
        <div class="button-group text-center">
          <a href="/users/<%=user[0].id%>">
            <b><div class="button small small-4 fuzzy-search-button"><%= image_tag('100pxWhiteLogo.png', :alt=>'Mentorship', size: "50x50")%></div></b>
          </a>
          <a href="<%=user[0].public_profile_url%>" target="_blank">
            <b><div id="tabs-3-linkedin-button" class="button small small-4 fuzzy-search-button"><i class="step fi-social-linkedin size-60"></i></div></b>
          </a>
          <%= link_to matches_path(:match => { :receiver_id => "#{user[0].id}" }), {:method => :post} do %>
            <b><div class="button warning small-4 small fuzzy-search-button"><i class='step fi-like size-60'></i></div></b>
          <% end %>
        </div>
      </div>
    </div>

  <hr class="style-three">
<% end %>

</div>

app/views/users/new.html.erb
<h1>This is the Users New</h1>
<a href="/auth/linkedin">Click here to login to your LinkedIn Account and create your Mentor Match Account</a>

<!-- <%= link_to 'Log in with LinkedIn', sessions_create_path %> -->

app/views/users/show.html.erb
<h1 class="text-center"><%= @user.first_name %> <%= @user.last_name %></h1>
<% if @user.status == 'available' %>
  <div class="row">
    <p class="small-1 columns"></p>
    <div class="small-10 columns text-center">
      <% if @user.type == 'Mentor' %>
        <%= @user.first_name %> is Offering Mentorship!
      <% else %>
        <%= @user.first_name %> is Seeking Mentorship
      <% end %>
    </div>
    <p class="small-1 columns"></p>
    </div>
  </div>
  <br>
<% end %>


  <div class="row">
    <p class="small-1 columns"></p>
    <div class="small-4 columns">
      <%=image_tag @user.picture_url %>
    </div>
    <div class="small-7 columns">
      <small><%= @user.current_title %> at</small><br>
      <b><%= @user.current_company%></b><br>
      <small><%= @user.location %></small><br>
    </div>
  </div>


<!-- If errors - place here -->
<% if @errors %>
  <% @errors.each do |error| %>
    <br>
    <div class="row">
      <div class="small-3 columns text-center">
        <i id="error-glyphicon-notification" class="step fi-alert size-36"></i>
      </div>
      <div class="small-9 columns text-center">
        <b><%=error%></b>
      </div>
    </div>
  <% end %>
<% end %>
<hr class="style-two">


  <div class="row">
    <div class="small-12 small-centered columns text-center">
      <i><%= @user.mission_statement %></i>
    </div>
    <!-- <i class="step fi-pencil size-24"></i> -->
  </div>
  <br>

  <% if @user.id != current_user.id %>
    <div class="row">
      <p class="small-1 columns"></p>
      <div class="small-10 columns">
        <%= link_to matches_path(:match => { :receiver_id => "#{@user.id}" }), {:method => :post} do %>
          <div class="button expanded success"><i class='step fi-shuffle size-36'></i><br>Connect!</div>
        <% end %>
      </div>
      <p class="small-1 columns"></p>
    </div>
  <%end%>

  <% if @user == current_user && (@interests - @user.interests).length != 0%>
  <div class="row">
    <p class="small-1 columns"></p>

    <div id="add-interest-button-user-show">

      <div class="small-10 columns text-center">
      <%= form_for(:user_interests, url: user_interests_path, html: {method: "create"}) do |f| %>

      <div class='interest-options-holder'>
      <%=render partial: 'interest_option_form' %>
      </div>
      <p class="small-1 columns"></p>
    </div>

    <div class="row">
      <div class="button-group expanded">
        <p class="small-3 columns"></p>
            <b><%= f.submit value="Add Interest!", class: "small-6 columns text-center warning button" %></b>
          <% end %>
        <p class="small-3 columns"></p>
      </div>
    </div>

    </div>
  </div>
<%end%>

    <h3 class="text-center"><%= current_user == @user ? "My" : "#{@user.first_name}'s"%> Interests</h3>
    <br>
    <div class="row" id="interest-container-user-show">
    <% if @user.interests.length > 0 %>
      <% @user.interests.each do |interest| %>
        <div class="small-6 columns">
          <a href="/interests/<%=interest.id%>" class="button expanded professional-interest-button"><b><%= interest.name %></b></a>
        </div>

    <% end %>
    </div>
  <% else %>
     <% if @user == current_user %>
      <div class="small-12 columns text-center" id="warning-if-no-interests">
        <p>You don't have any interests yet...<br> Add some using the form above!</p>
      </div>
    <% end %>
  <% end %>


<hr class="style-two">

<% if @user == current_user %>
  <div class="row">
    <div class="button-group expanded">
      <p class="small-3 columns"></p>
      <a href="/users/<%=current_user.id%>/edit" class="small-6 columns button warning"><i class="step fi-pencil size-36"></i><br><b>Edit My Profile</b></a>
      <p class="small-3 columns"></p>
    </div>
  </div>
<hr class="style-three">
<% end %>