config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'
  get 'demo', to: 'welcome#demo'
  resources :users
  get '/users/:id/finish', to: 'users#finish', as: 'users_finish'
  post '/users/:id/finish', to: 'users#initialize_new_user'


  resources :user_interests, only: [:create, :destroy]
  resources :interests, only: [:show]

  resources :matches, only: [:index, :create, :update, :destroy]


  resources :conversations, only: [:index, :destroy] do
    resources :messages, only: [:index, :create, :destroy]
  end

  resources :searches, only: [:index]

  get '/auth/linkedin/callback', to: 'sessions#create', as: 'sessions_create'
  get '/auth/failure', to:'sessions#failure'
  get '/logout', to: 'sessions#destroy', as: 'logout'
  get '/deleteuserinterest/:id', to: 'user_interests#destroy', as: 'user_interest_delete'

end

app/models/match.rb
class Match < ActiveRecord::Base
  validates :initiator_id, :receiver_id, :type, presence: true
  validates_uniqueness_of :initiator_id, :scope => :receiver_id, :message => ": This match already exists! View your Requests page."
  # validates_uniqueness_of :mentor_id, :scope => :mentee_id

  belongs_to :conversation, class_name: 'Conversation'
  belongs_to :initiator, class_name: 'User'
  belongs_to :receiver, class_name: 'User'
  belongs_to :mentor
  belongs_to :mentee

end

app/controllers/matches_controller.rb
class MatchesController < ApplicationController
  before_action :allow_user, :finish_profile

  def index
    mentor? ? @matches = AcceptedMatch.where(mentor_id: current_user.id) : @matches = AcceptedMatch.where(mentee_id: current_user.id)
    bot1matches = AcceptedMatch.where(initiator_id: 1)
    bot2matches = AcceptedMatch.where(initiator_id: 2)
# binding.pry
    bots = bot1matches + bot2matches
    @matches -= bots
    @matches_pending_my_decision = PendingMatch.where(receiver_id: current_user.id)
    @matches_pending_others_decision = PendingMatch.where(initiator_id: current_user.id)
  end

  def create
    @match = PendingMatch.new(match_params)
    @match.initiator_id = current_user.id

    if mentor?
      @match.mentor = current_user
      @match.mentee = @match.receiver
    else
      @match.mentor = @match.receiver
      @match.mentee = current_user
    end

    @convo = Conversation.find_or_create_by(mentor: @match.mentor, mentee: @match.mentee)

    @match.conversation_id = @convo.id

    if @match.save
      redirect_to '/matches'
    else
      @errors = @match.errors.full_messages
      render 'welcome/show'
    end
  end

  def update
    @match = Match.find(params[:id])

    @match.assign_attributes(match_params)
    if request.xhr? && @match.save
      render partial: 'matches_index_tab2_partial', locals: {matches: @matches}, layout: false
    elsif @match.save
      redirect_to '/matches'
    else
      @errors = @match.errors.full_messages
      render 'index'
    end
  end

  def destroy
    @match = Match.find(params[:id])
    @match.destroy
    redirect_to '/matches'
  end

  private

    def match_params
      params.require(:match).permit(:type,
                                    :receiver_id,
                                    :initiator_id)
    end

end

app/helpers/matches_helper.rb
module MatchesHelper
end

app/views/matches/_matches_index_tab1_partial.html.erb
<% @matches_pending_my_decision.each do |decision| %>
<a href="/users/<%=decision.initiator.id%>">
  <div class="row">
    <div class="small-4 large-4 columns">
      <%= image_tag decision.initiator.picture_url %>
    </div>
    <div class="small-8 large-8 columns">
      <b><%= decision.initiator.first_name %> <%= decision.initiator.last_name %></b><br>
      <small><%= decision.initiator.current_title %> at</small><br>
      <b><%= decision.initiator.current_company%></b><br>
    </div>
  </div>
</a>
  <hr class="style-two">

  <div class="row">
    <div class="small-12 small-centered columns text-center"><small><i><%= decision.initiator.mission_statement %></i></small></div>
  </div>

  <hr class="style-two">

  <div class="row">
    <div class="small-12 columns">
      <div class="button-group text-center">
      <%= link_to match_path(decision.id, :match => { :type => "AcceptedMatch" }), {:method => :put} do %>
        <div class="button small small-4 success"><i class='step fi-like size-60'></i></div>
      <% end %>
      <%= link_to match_path(decision.id), {:method => :delete} do %>
        <div class="button small small-4 warning"><i class='step fi-dislike size-60'></i></div>
      <% end %>
      <%= link_to match_path(decision.id, :match => { :type => "BlockedMatch" }), {:method => :put} do %>
        <div class="button small small-4 alert"><i class='step fi-prohibited size-60'></i></div>
      <% end %>
      </div>
    </div>
  </div>
  <hr class="style-three">
<% end %>

app/views/matches/_matches_index_tab2_partial.html.erb
<% @matches.each do |match| %>
  <% if current_user.type == "Mentor" %>
  <a href="/users/<%=match.mentee.id%>">
    <div class="row">
      <div class="small-4 large-4 columns">
        <%= image_tag match.mentee.picture_url %>
      </div>
      <div class="small-8 large-8 columns">
        <b><%= match.mentee.first_name %> <%= match.mentee.last_name %></b><br>
        <small><%= match.mentee.current_title %> at</small><br>
        <b><%= match.mentee.current_company%></b><br>
      </div>
    </div>
  </a>

  <hr class="style-two">

    <div class="row">
      <div class="small-12 small-centered columns text-center"><small><i><%= match.mentee.mission_statement %></i></small></div>
    </div>

  <hr class="style-two">
    <div class="row">
      <div class="small-12 columns">
        <div class="button-group text-center" id="jackie-button-group-left-button">
        <%= link_to conversations_path do %>
          <div class="button small small-4"><i class='step fi-mail size-60'></i></div>
        <% end %>
        <%= link_to match_path(match.id), {:method => :delete} do %>
          <div class="button small small-4 warning"><i class='step fi-lock size-60'></i></div>
        <% end %>
        <%= link_to match_path(match.id, :match => { :type => "BlockedMatch" }), {:method => :put} do %>
          <div class="button small small-4 alert block-button-to-hide-profile"><i class='step fi-prohibited size-60'></i></div>
        <% end %>
        </div>
      </div>
    </div>
  <% else %>
  <a href="/users/<%=match.mentor.id%>">
    <div class="row">
      <div class="small-4 large-4 columns">
        <%= image_tag match.mentor.picture_url %>
      </div>
      <div class="small-8 large-8 columns">
        <b><%= match.mentor.first_name %> <%= match.mentor.last_name %></b><br>
        <small><%= match.mentor.current_title %> at</small><br>
        <b><%= match.mentor.current_company%></b><br>
      </div>
    </div>
  </a>
  <hr class="style-two">

    <div class="row">
      <div class="small-12 small-centered columns text-center"><small><i><%= match.mentor.mission_statement %></i></small></div>
    </div>

  <hr class="style-two">
    <div class="row">
      <div class="small-12 columns">
        <div class="button-group expanded text-center">
        <%= link_to conversations_path do %>

          <div class="button small small-4 success"><i class='step fi-mail size-60'></i></div>
        <% end %>
        <%= link_to match_path(match.id, :match => { :type => "ClosedMatch" }), {:method => :put} do %>
          <div class="button small small-4 warning"><i class='step fi-lock size-60'></i></div>
        <% end %>
        <%= link_to match_path(match.id, :match => { :type => "BlockedMatch" }), {:method => :put} do %>
          <div class="button small small-4 alert"><i class='step fi-prohibited size-60'></i></div>
        <% end %>
        </div>
      </div>
    </div>
  <% end %>

  <hr class="style-three">

<% end %>

app/views/matches/_mentee_match_partial.html.erb
  <div class="row">
    <div class="small-4 large-4 columns">
      <a href="<%=match.mentee.public_profile_url%>" target="_blank"><%= image_tag match.mentee.picture_url %></a>
    </div>
    <div class="small-8 large-8 columns">
      <b><%= match.mentee.first_name %> <%= match.mentee.last_name %></b><br>
      <small><%= match.mentee.current_title %> at</small><br>
      <b><%= match.mentee.current_company%></b><br>
    </div>
  </div>

<hr class="style-two">

  <div class="row">
    <div class="small-12 small-centered columns text-center"><small><i><%= match.mentee.mission_statement %></i></small></div>
  </div>

<hr class="style-two">
  <div class="row">
    <div class="small-12 columns">
      <div class="button-group text-center">
      <%= link_to match_path(match.id, :match => { :type => "AcceptedMatch" }), {:method => :put} do %>
        <div class="button success"><i class='step fi-like size-36'></i><br>Accept</div>
      <% end %>
      <%= link_to match_path(match.id), {:method => :delete} do %>
        <div class="button warning"><i class='step fi-dislike size-36'></i><br>Reject</div>
      <% end %>
      <%= link_to match_path(match.id, :match => { :type => "BlockedMatch" }), {:method => :put} do %>
        <div class="button alert"><i class='step fi-prohibited size-36'></i><br>Block</div>
      <% end %>
      </div>
    </div>
  </div>

app/views/matches/_mentor_match_partial.html.erb
  <div class="row">
    <div class="small-4 large-4 columns">
      <a href="<%=match.mentor.public_profile_url%>" target="_blank"><%= image_tag match.mentor.picture_url %></a>
    </div>
    <div class="small-8 large-8 columns">
      <b><%= match.mentor.first_name %> <%= match.mentor.last_name %></b><br>
      <small><%= match.mentor.current_title %> at</small><br>
      <b><%= match.mentor.current_company%></b><br>
    </div>
  </div>

<hr class="style-two">

  <div class="row">
    <div class="small-12 small-centered columns text-center"><small><i><%= match.mentor.mission_statement %></i></small></div>
  </div>

<hr class="style-two">
  <div class="row">
    <div class="small-12 columns">
      <div class="button-group text-center">
      <%= link_to match_path(match.id, :match => { :type => "AcceptedMatch" }), {:method => :put} do %>
        <div class="button success"><i class='step fi-like size-36'></i><br>Accept</div>
      <% end %>
      <%= link_to match_path(match.id), {:method => :delete} do %>
        <div class="button warning"><i class='step fi-dislike size-36'></i><br>Reject</div>
      <% end %>
      <%= link_to match_path(match.id, :match => { :type => "BlockedMatch" }), {:method => :put} do %>
        <div class="button alert"><i class='step fi-prohibited size-36'></i><br>Block</div>
      <% end %>
      </div>
    </div>
  </div>

app/views/matches/index.html.erb
<link href='https://fonts.googleapis.com/css?family=Open+Sans' rel='stylesheet' type='text/css'>

<h1 class="text-center"><%=current_user.first_name%>'s Requests</h1>

<div class="row">
  <div class="small-12 text-center columns">
  <ul class="tabs-bar">
    <li class="active"><a class="text-center" href="#tabs-1">Requests</a></li>
    <li><a class="text-center" href="#tabs-2">My <%= current_user.type == "Mentor" ? "Protegés" : "Mentors"%></a></li>
    <li><a class="text-center" href="#tabs-3">Pending</a></li>
  </ul>
  </div>
</div>

  <div class="tab-content" id="tabs-1">
    <div class="container">
      <% if @matches_pending_my_decision.length > 0 %>
          <%= render 'matches_index_tab1_partial' %>
      <% else %>

        <p class='text-center'>It looks like you don't have any requests from <%= current_user.type == "Mentor" ? "Protegés" : "Mentors"%>.

        Check back later!</p>

      <% end %>
    </div>
  </div>

  <div class="tab-content" id="tabs-2">
    <div class="container parent-container-to-remove-profile-when-blocked">
      <% if @matches.length > 0 %>
        <%= render 'matches_index_tab2_partial' %>
      <% else %>

        <h3 class="text-center"><b>On no!</b></h3>
        <p class="text-center">It looks like you don't<br>have any <%= current_user.type == "Mentor" ? "Protegés" : "Mentors"%>!</p>
        <p class="text-center">Connect with a <%= current_user.type == "Mentor" ? "Protegé" : "Mentor"%> today!</p>

        <hr class="style-two">

        <p><a href="/users" class="button expanded success"><i class='step fi-shuffle size-36'></i><br>Click here</a></p>


      <% end %>
    </div>
  </div>

  <div class="tab-content" id="tabs-3">
    <div class="container">
      <% if @matches_pending_others_decision.length > 0 %>
        <% @matches_pending_others_decision.each do |decision| %>
          <a href="/users/<%=decision.receiver.id%>">
          <div class="row">
            <div class="small-4 columns"><%= image_tag decision.receiver.picture_url %></div>
            <div class="small-8 columns">
              <b><%= decision.receiver.first_name %> <%= decision.receiver.last_name %></b><br>
              <small><%= decision.receiver.current_title %> at</small><br>
              <b><%= decision.receiver.current_company%></b><br>
            </div>
          </div>
          </a>

        <hr class="style-two">

          <div class="row">
            <div class="small-12 small-centered columns text-center">
              <small><i><%= decision.receiver.mission_statement %></i></small>
            </div>
          </div>

        <hr class="style-two">

          <div class="row">
            <div class="small-12 columns">
              <div class="button-group text-center">
                <a href="<%=decision.receiver.public_profile_url%>" target='_empty' ><div class="button small small-6" id="tabs-3-linkedin-button"><i class="step fi-social-linkedin size-60"></i></div></a>
                <%= link_to match_path(decision.id), {:method => :delete} do %>
                  <div class="button small small-6 alert"><i class='step fi-x size-60'></i></div>
                <% end %>
              </div>
            </div>
          </div>

        <hr class="style-three">
        <% end %>
      <% else %>

        <h3 class="text-center"><b>On no!</b></h3>
        <p class="text-center">It looks like you don't<br>have any <%= current_user.type == "Mentor" ? "Protegés" : "Mentors"%>!</p>
        <p class="text-center">Connect with a <%= current_user.type == "Mentor" ? "Protegé" : "Mentor"%> today!</p>

        <hr class="style-two">

        <p><a href="/users" class="button expanded success"><i class='step fi-shuffle size-36'></i><br>Click here</a></p>

      <% end %>
    </div>
  </div>
</div>
<!-- <script src="//code.jquery.com/ui/1.11.4/jquery-ui.js"></script>
<script>
$(function() {
  $( "#tabs" ).tabs();
});
</script>
 -->